const Q = window.YUE_QUESTIONS || [];
const SUBJECT_NAMES = {PHY:"運動生理",AGE:"發展老化",PATH:"病理風險",PSY:"運動心理",SAFE:"急救安全",NUT:"營養體控",EXRX:"運動處方"};
const STORE_KEY="yue_fit_quiz_state_v02";
const ACTIVE_KEY="yue_fit_active_quiz_v02";
const DATA_VERSION="2026-09-05-v08";
const EMPTY_LEARNING={attempts:0,correct:0,wrong:0,streak:0,mastery:"未學習",lastSeen:null,nextReview:null,lapses:0};
const defaultState={schema:2,dataVersion:DATA_VERSION,learning:{},favorites:{},settings:{sound:true},lastMode:null,currentSubject:"ALL"};
function clone(x){return JSON.parse(JSON.stringify(x));}
function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORE_KEY)||"null");if(!raw||raw.schema!==2)return clone(defaultState);return {...clone(defaultState),...raw,learning:raw.learning||{},favorites:raw.favorites||{},settings:{...defaultState.settings,...(raw.settings||{})}}}catch(e){return clone(defaultState)}}
let state=loadState();
function saveState(){try{localStorage.setItem(STORE_KEY,JSON.stringify(state));return true}catch(e){showHomeNotice("這台裝置無法儲存進度，請先匯出備份或檢查Safari網站資料設定。","bad");return false}}
function getLearning(uid){return state.learning[uid]||EMPTY_LEARNING;}
function ensureLearning(uid){if(!state.learning[uid])state.learning[uid]=clone(EMPTY_LEARNING);return state.learning[uid];}
function intervalDays(streak){if(streak<=1)return 1;if(streak===2)return 3;if(streak===3)return 7;if(streak===4)return 14;return 30;}
function updateLearning(q,correct){const s=ensureLearning(q.uid),now=Date.now();s.attempts++;s.lastSeen=now;if(correct){s.correct++;s.streak++;const acc=s.correct/s.attempts;s.mastery=(s.attempts>=3&&s.streak>=3&&acc>=.8)?"已熟悉":"學習中";s.nextReview=now+intervalDays(s.streak)*86400000}else{s.wrong++;s.streak=0;s.lapses++;s.mastery="答錯待複習";s.nextReview=now+6*3600000}saveState();}
function questionScore(q){const s=getLearning(q.uid),now=Date.now(),isNew=s.attempts===0?1:0;let due=0;if(s.nextReview&&s.nextReview<=now)due=Math.min(1,.6+(now-s.nextReview)/(7*86400000)*.4);const weakness=Math.min(1,(s.attempts?s.wrong/s.attempts:0)*.65+Math.min(1,s.lapses/3)*.25+(s.mastery==="答錯待複習"?.1:0));const recent=s.lastSeen?Math.max(0,1-(now-s.lastSeen)/(2*86400000)):0;return 40*due+25*weakness+15*(q.exam_importance||.35)+10*isNew+5-15*recent;}
function subjectFilter(q){return state.currentSubject==="ALL"||q.subject_code===state.currentSubject;}
function buildPool(mode){let arr=Q.filter(subjectFilter),now=Date.now();if(mode==="review")arr=arr.filter(q=>{const s=getLearning(q.uid);return s.mastery==="答錯待複習"||(s.nextReview&&s.nextReview<=now)});if(mode==="new")arr=arr.filter(q=>getLearning(q.uid).attempts===0);if(mode==="core")arr=arr.filter(q=>q.core400);return arr;}
function chooseSession(mode,n=20){let arr=buildPool(mode).slice();if(!arr.length)return[];arr.sort((a,b)=>mode==="core"?((b.exam_importance||0)-(a.exam_importance||0)||questionScore(b)-questionScore(a)):questionScore(b)-questionScore(a));const top=arr.slice(0,Math.max(n*3,n));shuffle(top);return top.slice(0,Math.min(n,top.length));}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a;}
let quiz=null,timerInt=null;
function serializeQuiz(){if(!quiz)return null;return {...quiz,questions:quiz.questions.map(q=>q.uid)};}
function persistQuiz(){try{if(quiz)localStorage.setItem(ACTIVE_KEY,JSON.stringify(serializeQuiz()));else localStorage.removeItem(ACTIVE_KEY)}catch(e){}}
function restoreQuiz(){try{const raw=JSON.parse(localStorage.getItem(ACTIVE_KEY)||"null");if(!raw||!Array.isArray(raw.questions))return null;const by=Object.fromEntries(Q.map(q=>[q.uid,q]));const qs=raw.questions.map(u=>by[u]).filter(Boolean);if(!qs.length)return null;return {...raw,questions:qs}}catch(e){return null}}
function clearQuiz(){quiz=null;try{localStorage.removeItem(ACTIVE_KEY)}catch(e){}clearInterval(timerInt);}
function renderHome(){showScreen("home");renderHomeStatsOnly();renderSubjectChips();updateNetworkStatus();const saved=restoreQuiz();if(saved&&!saved.finished)showHomeNotice(`有一場尚未完成的${saved.kind==="exam"?"模擬考":"刷題"}（${saved.index+1}/${saved.questions.length}）。<button onclick="resumeQuiz()">繼續</button>`,"resume");}
function renderHomeStatsOnly(){const vals=Object.values(state.learning),mastered=vals.filter(x=>x.mastery==="已熟悉").length,wrong=vals.filter(x=>x.mastery==="答錯待複習").length,touched=vals.filter(x=>x.attempts>0).length;const due=Q.filter(q=>{const s=getLearning(q.uid);return s.nextReview&&s.nextReview<=Date.now()}).length;if($("#mastered"))$("#mastered").textContent=mastered;if($("#wrongCount"))$("#wrongCount").textContent=wrong;if($("#dueCount"))$("#dueCount").textContent=due;if($("#coverage"))$("#coverage").textContent=`${touched} / 785`;if($("#coverageFill"))$("#coverageFill").style.width=`${Math.round(touched/785*100)}%`;}
function renderSubjectChips(){const c=$("#subjectChips");c.innerHTML=`<button class="chip ${state.currentSubject==="ALL"?"active":""}" onclick="setSubject('ALL')">全部七科</button>`+Object.entries(SUBJECT_NAMES).map(([k,v])=>`<button class="chip ${state.currentSubject===k?"active":""}" onclick="setSubject('${k}')">${v}</button>`).join("");}
function setSubject(code){state.currentSubject=code;saveState();renderSubjectChips();}
function showHomeNotice(html,type=""){const n=$("#homeNotice");if(!n)return;n.className=`notice ${type||""}`;n.innerHTML=html;}
function hideHomeNotice(){const n=$("#homeNotice");if(n){n.className="notice hidden";n.innerHTML=""}}
function startStudy(mode){hideHomeNotice();const n=mode==="review"?15:20,qs=chooseSession(mode,n);if(!qs.length){const subject=state.currentSubject==="ALL"?"目前":"這個科目目前";showHomeNotice(mode==="review"?`${subject}沒有到期複習題。你可以先做新題學習。`:`${subject}沒有符合條件的題目。`);return}quiz={kind:"study",mode,questions:qs,index:0,answered:false,selected:null,correct:0,results:[],wrongUids:[],started:Date.now(),finished:false};state.lastMode=mode;saveState();persistQuiz();renderQuestion();}
function subjectQuota(n){return n===50?{PHY:9,AGE:7,PATH:6,PSY:9,SAFE:8,NUT:7,EXRX:4}:{PHY:18,AGE:14,PATH:12,PSY:17,SAFE:16,NUT:15,EXRX:8};}
function mulberry32(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffleWith(a,rng){for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a;}
function pickSubjectExam(candidates,count,usedClusters,rng){const cand=shuffleWith(candidates.slice(),rng),selected=[],topicCounts={},topicCap=Math.max(2,Math.ceil(count*.40));const add=q=>{selected.push(q);const t=q.topic||"__NONE__";topicCounts[t]=(topicCounts[t]||0)+1;if(q.repeat_cluster)usedClusters.add(q.repeat_cluster)};for(const q of cand){if(selected.length>=count)break;const t=q.topic||"__NONE__";if(q.repeat_cluster&&usedClusters.has(q.repeat_cluster))continue;if(t!=="__NONE__"&&(topicCounts[t]||0)>=topicCap)continue;add(q)}if(selected.length<count){const chosen=new Set(selected.map(q=>q.uid));for(const q of cand){if(selected.length>=count)break;if(chosen.has(q.uid))continue;if(q.repeat_cluster&&usedClusters.has(q.repeat_cluster))continue;add(q);chosen.add(q.uid)}}if(selected.length<count){const chosen=new Set(selected.map(q=>q.uid));for(const q of cand){if(selected.length>=count)break;if(chosen.has(q.uid))continue;add(q);chosen.add(q.uid)}}return selected;}
function blockOfSubject(code){if(["PHY","AGE"].includes(code))return 1;if(["EXRX","PATH","PSY"].includes(code))return 2;return 3;}
function startExam(kind){const n=kind==="exam50"?50:100,arr=kind==="core100"?Q.filter(q=>q.core400):Q.slice(),quota=subjectQuota(n),selected=[],usedClusters=new Set();const seed=(Date.now()^(Math.random()*0xffffffff))>>>0,rng=mulberry32(seed);Object.entries(quota).forEach(([code,count])=>selected.push(...pickSubjectExam(arr.filter(q=>q.subject_code===code),count,usedClusters,rng)));if(kind==="exam3block"){selected.sort((a,b)=>blockOfSubject(a.subject_code)-blockOfSubject(b.subject_code));for(const b of[1,2,3]){const inds=selected.map((q,i)=>blockOfSubject(q.subject_code)===b?i:-1).filter(i=>i>=0),items=shuffleWith(inds.map(i=>selected[i]),rng);inds.forEach((ix,k)=>selected[ix]=items[k])}}else shuffleWith(selected,rng);quiz={kind:"exam",mode:kind,questions:selected,index:0,answers:{},correct:0,wrongUids:[],started:Date.now(),seed,timeLimit:(kind==="exam3block"?40:(n===50?60:120))*60,blockStarted:kind==="exam3block"?Date.now():null,finished:false};persistQuiz();startTimer();renderQuestion();}
function startTimer(){clearInterval(timerInt);paintTimer();timerInt=setInterval(()=>{if(!quiz||quiz.kind!=="exam")return;paintTimer();const base=quiz.mode==="exam3block"?(quiz.blockStarted||quiz.started):quiz.started;const remain=Math.max(0,quiz.timeLimit-Math.floor((Date.now()-base)/1000));if(remain<=0){clearInterval(timerInt);onTimerExpired()}},1000)}
function paintTimer(){if(!quiz||quiz.kind!=="exam")return;const isBlocks=quiz.mode==="exam3block",base=isBlocks?(quiz.blockStarted||quiz.started):quiz.started;const elapsed=Math.floor((Date.now()-base)/1000),remain=Math.max(0,quiz.timeLimit-elapsed),el=$("#timer");if(el)el.textContent=`${String(Math.floor(remain/60)).padStart(2,"0")}:${String(remain%60).padStart(2,"0")}`;}
function currentBlock(){return quiz&&quiz.mode==="exam3block"?blockOfSubject(quiz.questions[quiz.index].subject_code):null;}
function onTimerExpired(){if(quiz&&quiz.mode==="exam3block"){const b=currentBlock();if(b<3){const next=quiz.questions.findIndex((q,i)=>i>quiz.index&&blockOfSubject(q.subject_code)===b+1);if(next>=0){quiz.index=next;quiz.blockStarted=Date.now();persistQuiz();renderQuestion();return}}}finishQuiz(true);}
function renderQuestion(){showScreen("quiz");const q=quiz.questions[quiz.index];$("#qIndex").textContent=`${quiz.index+1} / ${quiz.questions.length}`;$("#timer").classList.toggle("hidden",quiz.kind!=="exam");$("#submitExamTop").classList.toggle("hidden",quiz.kind!=="exam");const prevCrossBlock=quiz.mode==="exam3block"&&quiz.index>0&&blockOfSubject(quiz.questions[quiz.index-1].subject_code)!==currentBlock();$("#prevBtn").classList.toggle("hidden",quiz.index===0||prevCrossBlock);$("#qMeta").innerHTML=`<span class="badge">${SUBJECT_NAMES[q.subject_code]}</span>${quiz.mode==="exam3block"?`<span class="badge core">第${currentBlock()}段 · 40分鐘</span>`:""}${q.core400?'<span class="badge core">核心400</span>':""}${["S+","S","A+","A"].includes(q.priority_tier)?`<span class="badge hot">${q.priority_tier}級高頻</span>`:""}`;$("#qText").textContent=q.stem;$("#choices").innerHTML=q.choices.map((c,i)=>`<button class="choice" onclick="answerChoice(${i+1})"><b>${String.fromCharCode(65+i)}.</b> ${escapeHtml(c)}</button>`).join("");$("#feedback").className="feedback hidden";$("#feedback").innerHTML="";$("#nextBtn").classList.remove("hidden");$("#nextBtn").textContent=quiz.index===quiz.questions.length-1?(quiz.kind==="exam"?"檢查／交卷":"完成"):`下一題 →`;$("#favoriteBtn").textContent=state.favorites[q.uid]?"★ 已收藏":"☆ 收藏";if(quiz.kind==="exam"){const picked=quiz.answers[quiz.index];if(picked!=null)[...document.querySelectorAll(".choice")].forEach((b,i)=>b.classList.toggle("selected",i===picked-1))}else if(quiz.answered){paintStudyAnswer(q,quiz.selected,quiz.results[quiz.index])}persistQuiz();}
function paintStudyAnswer(q,idx,correct){const btns=[...document.querySelectorAll(".choice")];btns.forEach((b,i)=>{if(i===q.official_answer_index-1)b.classList.add("correct");if(i===idx-1&&!correct)b.classList.add("wrong");b.disabled=true});const fb=$("#feedback");fb.className=`feedback ${correct?"ok":"bad"}`;fb.innerHTML=correct?`<b>答對了 ✓</b><br>${escapeHtml(q.official_answer_text||"")}`:`<b>這題要再複習</b><br>正確答案：${q.official_answer_index}. ${escapeHtml(q.official_answer_text||"")}`;}
function answerChoice(idx){if(!quiz)return;const q=quiz.questions[quiz.index];if(quiz.kind==="exam"){quiz.answers[quiz.index]=idx;[...document.querySelectorAll(".choice")].forEach((b,i)=>b.classList.toggle("selected",i===idx-1));persistQuiz();return}if(quiz.answered)return;quiz.answered=true;quiz.selected=idx;const correct=idx===q.official_answer_index;quiz.results[quiz.index]=correct;if(correct)quiz.correct++;else{quiz.wrongUids.push(q.uid);scheduleSameSessionRetry(q.uid)}updateLearning(q,correct);paintStudyAnswer(q,idx,correct);renderHomeStatsOnly();persistQuiz();}
function scheduleSameSessionRetry(uid){const target=quiz.index+8;if(quiz.questions.slice(quiz.index+1).some(q=>q.uid===uid))return;const original=Q.find(q=>q.uid===uid);if(!original)return;const insertAt=Math.min(target,quiz.questions.length);quiz.questions.splice(insertAt,0,original);quiz.results.splice(insertAt,0,null);}
function prevQuestion(){if(!quiz||quiz.index<=0)return;quiz.index--;quiz.answered=quiz.kind==="study"&&quiz.results[quiz.index]!=null;quiz.selected=null;renderQuestion();}
function nextQuestion(){if(!quiz)return;if(quiz.kind==="study"&&!quiz.answered)return;if(quiz.index>=quiz.questions.length-1){if(quiz.kind==="exam")requestSubmitExam();else finishQuiz(false);return}const oldBlock=currentBlock();quiz.index++;if(quiz.mode==="exam3block"&&currentBlock()!==oldBlock)quiz.blockStarted=Date.now();quiz.answered=quiz.kind==="study"&&quiz.results[quiz.index]!=null;quiz.selected=null;renderQuestion();}
function requestSubmitExam(){if(!quiz||quiz.kind!=="exam")return;const unanswered=quiz.questions.length-Object.keys(quiz.answers).length;if(unanswered>0&&!confirm(`還有 ${unanswered} 題未作答，確定要交卷嗎？`))return;finishQuiz(false);}
function finishQuiz(timedOut=false){if(!quiz||quiz.finished)return;clearInterval(timerInt);quiz.finished=true;if(quiz.kind==="exam"){quiz.correct=0;quiz.wrongUids=[];quiz.questions.forEach((q,i)=>{const picked=quiz.answers[i],correct=picked===q.official_answer_index;if(correct)quiz.correct++;else quiz.wrongUids.push(q.uid);if(picked!=null)updateLearning(q,correct)})}try{localStorage.removeItem(ACTIVE_KEY)}catch(e){}renderResult(timedOut);}
function renderResult(timedOut=false){showScreen("result");const pct=Math.round(quiz.correct/quiz.questions.length*1000)/10;$("#score").textContent=`${pct}`;$("#scoreLabel").textContent=quiz.kind==="exam"?`${pct>=70?"及格 ✓":"未達70分"}${timedOut?" · 時間到":""}`:`答對 ${quiz.correct} / ${quiz.questions.length}`;const by={};quiz.questions.forEach((q,i)=>{by[q.subject_code]??={n:0,c:0};by[q.subject_code].n++;const correct=quiz.kind==="exam"?quiz.answers[i]===q.official_answer_index:quiz.results[i]===true;if(correct)by[q.subject_code].c++});$("#subjectBars").innerHTML=Object.entries(by).map(([code,x])=>{const p=Math.round(x.c/x.n*100);return `<div class="subject-row"><span>${SUBJECT_NAMES[code]}</span><div class="bar"><i style="width:${p}%"></i></div><b>${p}%</b></div>`}).join("");$("#wrongSummary").textContent=quiz.wrongUids.length?`這次有 ${quiz.wrongUids.length} 個錯誤作答，已自動進入弱點／複習系統。`:"這次沒有錯題。";}
function leaveQuiz(){if(!quiz){goHome();return}if(confirm("要離開目前進度嗎？系統會保留這場，回首頁可繼續。")){persistQuiz();clearInterval(timerInt);renderHome()}}
function resumeQuiz(){quiz=restoreQuiz();if(!quiz)return renderHome();if(quiz.kind==="exam")startTimer();renderQuestion();}
function goHome(){if(quiz&&!quiz.finished)persistQuiz();clearInterval(timerInt);quiz=null;renderHome();}
function toggleFavorite(){const q=quiz.questions[quiz.index];state.favorites[q.uid]=!state.favorites[q.uid];saveState();$("#favoriteBtn").textContent=state.favorites[q.uid]?"★ 已收藏":"☆ 收藏";}
function showFavorites(){showScreen("list");$("#listTitle").textContent="收藏題";const arr=Q.filter(q=>state.favorites[q.uid]);$("#listBody").innerHTML=arr.length?arr.map(q=>`<div class="list-card"><h3>${SUBJECT_NAMES[q.subject_code]} · ${q.uid}</h3><p>${escapeHtml(q.stem)}</p></div>`).join(""):`<div class="notice">目前還沒有收藏題。</div>`;}
function showWeak(){showScreen("list");$("#listTitle").textContent="錯題／待複習";const arr=Q.filter(q=>getLearning(q.uid).mastery==="答錯待複習").sort((a,b)=>(getLearning(b.uid).wrong||0)-(getLearning(a.uid).wrong||0));$("#listBody").innerHTML=arr.length?arr.map(q=>`<div class="list-card"><h3>${SUBJECT_NAMES[q.subject_code]} · 錯 ${getLearning(q.uid).wrong} 次</h3><p>${escapeHtml(q.stem)}</p></div>`).join(""):`<div class="notice">目前沒有待複習錯題。</div>`;}
function showStats(){showScreen("statsScreen");const data=Object.entries(SUBJECT_NAMES).map(([code,name])=>{const qs=Q.filter(q=>q.subject_code===code),learned=qs.filter(q=>getLearning(q.uid).attempts>0),mastered=qs.filter(q=>getLearning(q.uid).mastery==="已熟悉"),correct=learned.reduce((s,q)=>s+getLearning(q.uid).correct,0),attempts=learned.reduce((s,q)=>s+getLearning(q.uid).attempts,0);return{code,name,total:qs.length,touched:learned.length,mastered:mastered.length,acc:attempts?Math.round(correct/attempts*100):0}});$("#statsBody").innerHTML=data.map(x=>`<div class="list-card"><h3>${x.name}</h3><p>已接觸 ${x.touched}/${x.total} · 已熟悉 ${x.mastered} · 作答正確率 ${x.acc}%</p><div class="bar" style="margin-top:8px"><i style="width:${Math.round(x.touched/x.total*100)}%"></i></div></div>`).join("");}
function showSettings(){showScreen("settingsScreen");}
function exportProgress(){const blob=new Blob([JSON.stringify({schema:2,dataVersion:DATA_VERSION,exportedAt:new Date().toISOString(),state,activeQuiz:serializeQuiz()},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`月月體適能_學習進度_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importProgress(ev){const file=ev.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);if(!x.state||x.state.schema!==2)throw new Error();state=x.state;saveState();if(x.activeQuiz)try{localStorage.setItem(ACTIVE_KEY,JSON.stringify(x.activeQuiz))}catch(e){}alert("學習進度已匯入");renderHome()}catch(e){alert("這個檔案不是相容的月月體適能進度備份")}};reader.readAsText(file);}
function resetProgress(){if(confirm("確定要清除這台裝置的學習紀錄嗎？題庫本身不會刪除。")){state=clone(defaultState);saveState();try{localStorage.removeItem(ACTIVE_KEY)}catch(e){}renderHome();}}
function updateNetworkStatus(){const el=$("#deviceStatus");if(!el)return;const on=navigator.onLine;el.textContent=on?"● 已連線 · 離線快取啟用":"● 離線模式";el.className=`device-status ${on?"online":"offline"}`;}
function showScreen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));const el=$("#"+id);if(el)el.classList.remove("hidden");const nav=document.querySelector(".bottom-nav");if(nav)nav.classList.toggle("hidden",id==="quiz");}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function $(sel){return document.querySelector(sel)}
window.addEventListener("online",updateNetworkStatus);window.addEventListener("offline",updateNetworkStatus);window.addEventListener("beforeunload",()=>{if(quiz&&!quiz.finished)persistQuiz()});document.addEventListener("visibilitychange",()=>{if(document.hidden&&quiz&&!quiz.finished)persistQuiz()});
async function bootYueFitApp(){if(Q.length!==785){document.body.innerHTML='<div style="padding:30px;font-family:sans-serif">題庫載入失敗，請重新整理或清除舊快取。</div>';return}if("serviceWorker" in navigator){try{const reg=await navigator.serviceWorker.register("./sw.js?v=20260905-v08");await reg.update()}catch(e){console.warn("SW register failed",e)}}try{if(navigator.storage&&navigator.storage.persist)await navigator.storage.persist()}catch(e){}renderHome();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bootYueFitApp,{once:true});else bootYueFitApp();
